### PR TITLE
Send email with participants of a specific event and improve email

### LINKED ISSUE #88: Send list of participants via mail
Once sending mail is working it would be nice to automatically send a mail with the list of participants to a predefined adress of the responsible Meta, possibly given in event_data.php

### PR DESCRIPTION
**Pull request by am9zZWY**
closes #88

### CODE REVIEW

**Comment by am9zZWY** [comment]
@Pfonks

**Comment by Pfonks** [comment]
Looks good so far.

As you've said the code to automatically send the list once the event registration window closes needs to be added.

So far only names and mail adresses will be included in the sent data, to be useful we need to send all information otherwise provided within the .csv file.

**Comment by am9zZWY** [comment]
> So far only names and mail adresses will be included in the sent data, to be useful we need to send all information otherwise provided within the .csv file.

Ahh, so you want all the information from .csv file?

**Comment by Pfonks** [comment]
Yes, otherwise the person organizing event needs to contact an admin again to get the information from the .csv file and that is exactly what we want to change.

We also need to add a value holding the mailadress for the responsible organizer to every event - altough that should short work and easy to integrate.

**Comment by am9zZWY** [comment]
image

image

**Comment by am9zZWY** [comment]
Image of the email content
image

**Comment by Pfonks** [comment]
> The thing is, there are some uncleared questions:
> 
> * authorization of the sender?

I don't really understand this point, could you please clarify what you mean? Sender adress should be fsi@fsi - same as with the registration mails.

> * where should the email to which the list of participants should be sent be provided?

Exactly where you specified, in the event_data file seperately for each event. Altough the fsi@fsi fallback should probably be removed to prevent any issues with data protection. Altough we should probably build a check that only allows sending the lists to adresses ending in @student.uni-tuebingen.de .

> * spam prevention?

Probably best to create a file in the directory that is added to the ignore file for git and put all adresses with aliases there. While this needs some interevention from someone with access to the file on the server it at least takes away the issue of having to send the lists once a registration phase closes and puts all needed work potentially into a single session. Once the file contains a pair of alias and adress there is no more work needed and the list of people responsible people doesn't change much from term to term.

**Comment by luoe** [comment]
@am9zZWY would you like to elaborate on Maltes points or can I merge this one?

**Comment by Pfonks** [comment]
@am9zZWY What's the current status of this?

**Comment by Pfonks** [comment]
> @am9zZWY What's the current status of this?

:)

**Comment by am9zZWY** [comment]
Bildschirmfoto 2023-10-16 um 19 15 10

**Comment by am9zZWY** [comment]
@Pfonks @PhictionalOne @luoe

**Comment by Pfonks** [comment]
Looks pretty good so far, altough I'm still missing the verification for @student.uni-tuebingen.de - adresses.

I personally don't really like the option to send the list of participants through the use of a button. I'd much prefer the list to just be automatically sent if
a) the registration closes
b) somebody registers and the maximum number of participants is thus reached, or
c) someone cancels their registration - preferably containing only the relevant change and not the entire list

How do you feel about that instead of a button @am9zZWY @PhictionalOne ?

**Comment by am9zZWY** [comment]
I think option b) and c) are feasible. Option a) is a bit more tricky, I think.

**Comment by am9zZWY** [comment]
I don't understand why you need a verification of the student email address? It only sends to the responsible people specified in the event_config.php under
```php
"responsible" => [...]
```

**Comment by Pfonks** [comment]
> I don't understand why you need a verification of the student email address? It only sends to the responsible people specified in the event_config.php under
> 
> ```
> "responsible" => [...]
> ```

To make sure the list doesn't get send to external mail adresses because that would potentially entail needing to encrypt the data to be in compliance with GDPR laws.



> I think option b) and c) are feasible. Option a) is a bit more tricky, I think.

We could reuse your logging functionality and initially send a tokenized link to generate the mail to the adresses listed under "responsible".

**Comment by Pfonks** [comment]
> I personally don't like that the responsible persons mail address is readable in plain text in this Repo.
> 
> A workaround and still get the comfort feature of receiving a mail would be a mailinglist like `ersti-metas@fsi...`. But this would be a small administrative overhead for admins every planning phase.

We could use a file that is only stored on the server and add it to the .gitignore which contains all mail adresses stored in vars that are then imported into the event_data file. 

This could look like $MAIL['phi'], $MAIL['pfonks'], etc.

This has some overhead to it, altough once an adress is stored in the file it could be referenced again easily and having to enter new mail adresses once every 6 months beats having to pull the participants lists for a lot of events.

**Comment by luoe** [comment]
Just my two cents

> Looks pretty good so far, altough I'm still missing the verification for @student.uni-tuebingen.de - adresses.
> 
> I personally don't really like the option to send the list of participants through the use of a button. I'd much prefer the list to just be automatically sent if a) the registration closes b) somebody registers and the maximum number of participants is thus reached, or c) someone cancels their registration - preferably containing only the relevant change and not the entire list
> 
> How do you feel about that instead of a button @am9zZWY @PhictionalOne ?

I totally agree. But it also needs to be pointed out that this PR is already great from the current standpoint of the project. It's way better than having an admin sent the list of participants manually for every event (as this has been the case since the beginning of eei).




> I don't understand why you need a verification of the student email address? It only sends to the responsible people specified in the event_config.php under
> 
> ```
> "responsible" => [...]
> ```

> > I don't understand why you need a verification of the student email address? It only sends to the responsible people specified in the event_config.php under
> > ```
> > "responsible" => [...]
> > ```
> 
> To make sure the list doesn't get send to external mail adresses because that would potentially entail needing to encrypt the data to be in compliance with GDPR laws.
> 
> > I think option b) and c) are feasible. Option a) is a bit more tricky, I think.
> 
> We could reuse your logging functionality and initially send a tokenized link to generate the mail to the adresses listed under "responsible".

The problem would not be that the mail addresses of the metas are stored in the config.php (which is either way not stored in the Git repo), rather that this needs manual works. Some LDAP groups/assignments would be way easier (and could be done via the Keycloak web interface).
I would have this stored within the user management instead of in $MAIL['phi'], etc.

A mailing list could be created but again, this requires more manual intervention than assigning Metas to groups in LDAP and getting the information from Keycloak/LDAP.

**Comment by Pfonks** [comment]
For now I'd like to stick to just using a list of adresses in a file. While this may not be the solution we want to use in the long run it would enable us to actually merge this PR and reduce the maintenance by admins to inserting adresses into a file twice a year :smile:

**Pull request merged**
