### PR TITLE
Allow users to delete their reservation and add checks for successful registration and registration deletion

### PR DESCRIPTION
**Pull request by am9zZWY**
Allow users to delete their reservation by providing a link in the e-mail. Instead of having an ID, a registration ID is generated from the data the user provides and some static information about the event. When the deletion link is called, the user is presented with a prompt that allows him to delete his reservation. When deleting the reservation, the code searches through the CSV and generates, for each entry, an ID that is compared with the reservation ID that is already provided to the user.

### CODE REVIEW

**Comment by am9zZWY** [comment]
Furthermore, checks were implemented that only check if the CSV was written successfully.

**Review by Pfonks — COMMENTED** [review]
The changes look good to me - the only problem is the (as far as I am informed) currently missing service for sending out mails.

**Comment by PhictionalOne** [comment]
I really like your solution to the problem. But as @Pfonks wrote and I noted in #87 there is currently no reliable way to send out emails.

Sorry that I have to bring the bad news...

**Comment by am9zZWY** [comment]
Shit XD

**Pull request closed without merging**
