### PR TITLE
Link calendar data from FSI Cloud

### PR DESCRIPTION
**Pull request by am9zZWY**
- Add support for .ics files from FSI Cloud
- Add button to download .ics for event
- Include .ics attachment in confirmation email

In the future, this could be used to use the date, time, event data and more from FSI Cloud.

### CODE REVIEW

**Comment by am9zZWY** [comment]
@Pfonks @PhictionalOne

**Comment by Pfonks** [comment]
Personally I fell like the option to subscribe to the fsi server calendar is a great idea and should probably be the only option.

I think the few use cases in which .ics files are needed are outweighed by the disadvantage of not receiving automatic updates in case the schedule changes.

But I'm very interested to hear your takes on this question @am9zZWY and @PhictionalOne

**Comment by Pfonks** [comment]
Preferably the fsi calendar, probably worth looking into pushing the eei event data to the calendar (that is provided by Nextcloud Calendars) if possible.

For a single event I don't really think providing a .ics file will be used a lot if ever, probably faster for most people to just enter the event manually to their existing calendars if there are no updates anyway.

**Comment by PhictionalOne** [comment]
I personally would like a single event `.ics`. Something along the lines of a `"Add to calender"` Button is nice. 
The only thing is that, as @Pfonks said, the "normal" user would be faster doing it manually. The only people benefitting from it would be people with an OS or calendar program (partially) automating the "download ics -> load into calender" task.

Another take on that would be to embed the calender event in the confirmation email (that #102 introduces). A normal email/calendar program should be able to pick that up.

Coming to
> Preferably the fsi calendar, probably worth looking into pushing the eei event data to the calendar (that is provided by Nextcloud Calendars) if possible.

For me this would also be an ideal way to introduce events to the eei altogether. 
- The EEI could pull the calender
- filter `Ersti-*`/`*-Workshop` events in the future
- load `name`, `datetime`, `location`
- load additional parameters from event description.
  - obviously description
  - then some delimiter
  - json/yaml configuration for `max_participants`

Internationalisation (18n) could then be handled with the description being split into two parts.
The event title itself could look like `Ersti-Kastenlauf | Crate run` or so.

But this would look like a loooot of work to me.

**Comment by Pfonks** [comment]
@am9zZWY Could you quickly summarize your recent changes and give an update on the current status of this PR? :)

**Comment by am9zZWY** [comment]
This PR contains the following features & changes:

- an .ics file for the event, which is based on the information from the FSI Cloud .ics file is now attached in the registration mail. This happens when the event in the FSI Cloud contains the same Event ID, e.g., SP2 ("Spieleabend II") in the event description.

- an .ics file can now directly be downloaded from the EEI

- small format changes

TBD:
- move more information from the EEI to the FSI Cloud Calendar and only use information from the FSI Cloud Calendar #103

**Comment by am9zZWY** [comment]
@Pfonks @PhictionalOne @luoe

**Pull request merged**
